apiVersion: v1
kind: ConfigMap
metadata:
  name: task-management-config
  namespace: task-management
data:
  PORT: "3000"
  DB_PORT: "3306"
  DB_NAME: "database1"
  AWS_REGION: "ap-south-1"
  S3_BUCKET_NAME: "ekslogsbucketazmi"
