apiVersion: v1
kind: Secret
metadata:
  name: task-management-secret
  namespace: task-management
type: Opaque
stringData:
  DB_HOST: "database.cr2u8kkwoqke.ap-south-1.rds.amazonaws.com"
  DB_USER: "admin"
  DB_PASSWORD: "Admin12345"
